version: "3.7"
services:
  order-service:
    image: dejmartins/order-service:latest
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    environment:
      - ORDER_QUEUE_URI=${ORDER_QUEUE_URI}
      - ORDER_QUEUE_HOSTNAME=${ORDER_QUEUE_HOSTNAME}
      - ORDER_QUEUE_USERNAME=${ORDER_QUEUE_USERNAME}
      - ORDER_QUEUE_PASSWORD=${ORDER_QUEUE_PASSWORD}
      - ORDER_QUEUE_NAME=${ORDER_QUEUE_NAME}
      - USE_WORKLOAD_IDENTITY_AUTH=${USE_WORKLOAD_IDENTITY_AUTH}
      - ORDER_DB_URI=${ORDER_DB_URI}
      - ORDER_DB_NAME=${ORDER_DB_NAME}
      - ORDER_DB_COLLECTION_NAME=${ORDER_DB_COLLECTION_NAME}
    networks:
      - backend_services

networks:
  backend_services:
    driver: bridge
