version: "3.7"

services:
  order-service:
    image: dejmartins/order-service:latest
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    environment:
      - AZURE_SERVICEBUS_CONNECTION_STRING=
      - AZURE_SERVICEBUS_QUEUE=orders
    networks:
      - backend_services

networks:
  backend_services:
    driver: bridge
